services:

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  coordinador:
    build: ./coordinador
    command: ["images/logos.jpg", "images/output/salidaLogos.jpg", "${NUM_WORKERS}"]  # imagen, salida, cantidad de workers
    volumes:
      - ./images:/app/images               # acceso a las imágenes
    depends_on:
      - rabbitmq
      - redis
    environment:
      NUM_WORKERS: ${NUM_WORKERS}

  worker:
    build: ./worker
    deploy:
      replicas: ${NUM_WORKERS}
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - ./images:/app/images

volumes:
  rabbitmq_data: