services:
  nodo1:
    build: ./nodo
    container_name: nodo1
    networks:
      - red_nodos
    command: java Nodo 8080 nodo2 8081

  nodo2:
    build: ./nodo
    container_name: nodo2
    networks:
      - red_nodos
    command: java Nodo 8081 nodo1 8080 

  nodo3:
    build: ./nodo
    container_name: nodo3
    networks:
      - red_nodos
    command: java Nodo 8082 nodo4 8083

  nodo4:
    build: ./nodo
    container_name: nodo4
    networks:
      - red_nodos
    command: java Nodo 8083 nodo3 8082

networks:
  red_nodos:
    driver: bridge
