services:
  nodo1:
    build: ./
    container_name: nodo1
    ports:
      - "8080:8080"   # Mapea el puerto 8080 del contenedor al host
    networks:
      - red_nodos
    command: java -cp nodo.jar:gson.jar Nodo 8080 nodo2 8081 # Dirección del servidor y puerto de escucha

  nodo2:
    build: ./
    container_name: nodo2
    networks:
      - red_nodos
    command: java -cp nodo.jar:gson.jar Nodo 8081 nodo1 8080 # Dirección del cliente y puerto del servidor

networks:
  red_nodos:
    driver: bridge
