services:
  nodod:
    build: ./
    container_name: nodoD
    ports:
      - "8080:8080"   # Mapea el puerto 8080 del contenedor al host
    networks:
      - red_nodos
    command: java -cp nodo.jar:gson.jar NodoD

  nodoc1:
    build: ./
    container_name: nodoC1
    depends_on:
      - nodod
    networks:
      - red_nodos
    command: java -cp nodo.jar:gson.jar NodoC nodoD 12347
  
  nodoc2:
    build: ./
    container_name: nodoC2
    depends_on:
      - nodod
    networks:
      - red_nodos
    command: java -cp nodo.jar:gson.jar NodoC nodoD 12347

  nodoc3:
    build: ./
    container_name: nodoC3
    depends_on:
      - nodod
    networks:
      - red_nodos
    command: java -cp nodo.jar:gson.jar NodoC nodoD 12347

networks:
  red_nodos:
    driver: bridge
