apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinador
  template:
    metadata:
      labels:
        app: coordinador
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tipo
                operator: In
                values:
                  - aplicaciones
      containers:
        - name: coordinador
          image: bautista222221/coordinador:2.6
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: coordinador-service
spec:
  type: LoadBalancer
  selector:
    app: coordinador
  ports:
    - protocol: TCP
      port: 80       # Puerto público accesible
      targetPort: 5000  # Puerto del contenedor