services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"      # puerto RabbitMQ para AMQP
      - "15672:15672"    # interfaz web de management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  coordinator:
    build: ./coordinador
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python coordinador.py
    networks:
      - mining-net

  worker:
    build: ./worker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
    command: python worker.py
    networks:
      - mining-net
    deploy:
      replicas: 4  # Opcional: para levantar 4 workers iguales (requiere swarm)

networks:
  mining-net:
    driver: bridge
