apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 3  # Se puede ajustar según tus necesidades
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: bautista222221/worker:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: RABBITMQ_URL
          value: "rabbitmq:5672"
        - name: REDIS_URL
          value: "redis:6379"