apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinador
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinador
  template:
    metadata:
      labels:
        app: coordinador
    spec:
      containers:
      - name: coordinador
        image: bautista222221/coordinador:latest
        ports:
        - containerPort: 80
        env:
        - name: FLASK_ENV
          value: "development"
        - name: 3
          valueFrom:
            configMapKeyRef:
              name: coordinador-config
              key: NUM_WORKERS
