services:
  servidor:
    build: ./servidor
    container_name: servidor-tareas
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - red-tareas
    environment:
      - JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8  # Opcional, para evitar problemas de encoding

networks:
  red-tareas:
    driver: bridge